experiment_id: "default_offline"
model_save_dir: "saved_models"

device: 'cuda:0'  # Will use this device if available, otherwise wil use cpu

# Define networks architectures
networks:
  variational: True
  dtype : "float"
  encoder_q:
    hidden_conv_layers: 2
    n_filters: [16, 16, 8]  # first + hidden
    kernel_sizes: [3, 3, 5, 5]  # first + hidden + last
    strides: [1, 1, 1, 2]  # first + hidden + last
    out_channels: 16
  transformer_q:
    hidden_conv_layers: 2
    n_filters: [8, 8, 8]  # first + hidden
    kernel_sizes: [3, 3, 3, 3]  # first + hidden + last
    strides: [1, 1, 2, 2]  # first + hidden + last
    out_channels: 8  # Channels of latent q representation
  potential:
    hidden_conv_layers: 1
    in_shape: [8, 4, 4]  # Should be coherent with transformer output
    n_filters: [8, 8, 8]  # first + hidden + 1
    kernel_sizes: [3, 3, 3]  # first + hidden + last
    strides: [1, 1, 1]  # first + hidden + last
  encoder_p:
    hidden_conv_layers: 2
    n_filters: [48, 32, 16]  # first + hidden
    kernel_sizes: [3, 3, 3, 5]  # first + hidden + last
    strides: [ 1, 1, 1, 2]  # first + hidden + last
    out_channels: 16
  transformer_p:
    hidden_conv_layers: 2
    n_filters: [ 8, 8, 8 ]  # first + hidden
    kernel_sizes: [ 3, 3, 3, 3 ]  # first + hidden + last
    strides: [ 1, 1, 2, 2 ]  # first + hidden + last
    out_channels: 8  # Channels of latent q representation
  decoder:
    n_residual_blocks: 3
    n_filters: [32, 32, 32]
    kernel_sizes: [3, 3, 3, 3]

# Define HGN Integrator
integrator:
  method: "Leapfrog"

# Define optimization
optimization:
  epochs: 5
  batch_size: 16
  use_steps: 10
  # Learning rates
  encoder_lr: 1.5e-4
  transformer_lr: 1.5e-4
  hnn_lr: 1.5e-4
  decoder_lr: 1.5e-4

geco:
  alpha: 0.99
  tol: 1.0e-4 # per pixel error tolerance
  initial_lagrange_multiplier: 1.0
  lagrange_multiplier_param: 0.1
  # To train in a beta-vae fashion use the following parameters:
  # alpha: 0.0
  # tol: 0.0
  # initial_lagrange_multiplier: 1 / beta
  # lagrange_multiplier_param = 1.0