# Experiment ID
experiment_id: "overfit_test_p2"

# Define networks architectures
networks:
  encoder:
    hidden_conv_layers: 2
    n_filters: [16, 8, 8]  # cl + 1
    kernel_sizes: [3, 3, 3, 3]  # cl + 2
    strides: [1, 1, 1, 1]  # cl + 2
    out_channels: 8
  transformer:
    hidden_conv_layers: 2
    n_filters: [16, 16, 16]  # cl + 1
    kernel_sizes: [3, 3, 3, 3]  # cl + 2
    strides: [2, 2, 2, 1]  # cl + 2
    out_channels: 16  # Channels of q, and p splitted
  hamiltonian:
    hidden_conv_layers: 2
    in_shape: [16, 4, 4]  # Should be coherent with transformer output
    n_filters: [16, 32, 32, 32]
    kernel_sizes: [3, 3, 3, 3]
    strides: [1, 1, 1, 1]
  decoder:
    n_residual_blocks: 3
    n_filters: [16, 16, 16]
    kernel_sizes: [3, 3, 3, 3]

# Define optimization
optimization:
  epochs: 3000
  batch_size: 1
  # Learning rates
  encoder_lr: 1.5e-4
  transformer_lr: 1.5e-4
  hnn_lr: 1.5e-4
  decoder_lr: 1.5e-4